//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientPortal.Data.Contexts
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CakeContext : DbContext
    {
        public CakeContext()
            : base("name=CakeContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CakeAdvertiser> CakeAdvertisers { get; set; }
        public DbSet<CakeOffer> CakeOffers { get; set; }
        public DbSet<DailySummary> DailySummaries { get; set; }
    }
}
