//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientPortal.Data.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Click
    {
        public int click_id { get; set; }
        public int visitor_id { get; set; }
        public int request_session_id { get; set; }
        public System.DateTime click_date { get; set; }
        public int affiliate_id { get; set; }
        public string affiliate_name { get; set; }
        public int advertiser_id { get; set; }
        public string advertiser_name { get; set; }
        public int offer_id { get; set; }
        public string offer_name { get; set; }
        public int campaign_id { get; set; }
        public int creative_id { get; set; }
        public string creative_name { get; set; }
        public string sub_id_1 { get; set; }
        public string sub_id_2 { get; set; }
        public string sub_id_3 { get; set; }
        public string sub_id_4 { get; set; }
        public string sub_id_5 { get; set; }
        public string ip_address { get; set; }
        public string user_agent { get; set; }
        public string referrer_url { get; set; }
        public string request_url { get; set; }
        public string redirect_url { get; set; }
        public string country_code { get; set; }
        public string country_name { get; set; }
        public string region_code { get; set; }
        public string region_name { get; set; }
        public byte language_id { get; set; }
        public string language_name { get; set; }
        public string language_abbr { get; set; }
        public int isp_id { get; set; }
        public string isp_name { get; set; }
        public short device_id { get; set; }
        public string device_name { get; set; }
        public string operating_system_name { get; set; }
        public int browser_id { get; set; }
        public string browser_name { get; set; }
        public string disposition { get; set; }
        public string paid_action { get; set; }
        public int total_clicks { get; set; }
    }
}
