//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientPortal.Data.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPMReport
    {
        public CPMReport()
        {
            this.CampaignDrops = new HashSet<CampaignDrop>();
        }
    
        public int CPMReportId { get; set; }
        public int OfferId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public string Recipient { get; set; }
        public string Summary { get; set; }
        public string Conclusion { get; set; }
    
        public virtual Offer Offer { get; set; }
        public virtual ICollection<CampaignDrop> CampaignDrops { get; set; }
    }
}
