//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientPortal.Data.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailedReport
    {
        public int Id { get; set; }
        public string EmailTo { get; set; }
        public int EmailStatus { get; set; }
        public Nullable<System.DateTime> EmailStatusUpdated { get; set; }
        public int GeneratedReportId { get; set; }
    
        public virtual GeneratedReport GeneratedReport { get; set; }
    }
}
