//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientPortal.Data.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactClick
    {
        public FactClick()
        {
            this.FactConversions = new HashSet<FactConversion>();
        }
    
        public int ClickKey { get; set; }
        public int RegionKey { get; set; }
        public int CountryKey { get; set; }
        public Nullable<int> ConversionKey { get; set; }
    
        public virtual DimCountry DimCountry { get; set; }
        public virtual DimRegion DimRegion { get; set; }
        public virtual ICollection<FactConversion> FactConversions { get; set; }
    }
}
