//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientPortal.Data.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metric
    {
        public Metric()
        {
            this.MetricValues = new HashSet<MetricValue>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<MetricValue> MetricValues { get; set; }
    }
}
