//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientPortal.Data.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchCampaign
    {
        public SearchCampaign()
        {
            this.SearchDailySummaries = new HashSet<SearchDailySummary>();
        }
    
        public int SearchCampaignId { get; set; }
        public string SearchCampaignName { get; set; }
        public int AdvertiserId { get; set; }
    
        public virtual Advertiser Advertiser { get; set; }
        public virtual ICollection<SearchDailySummary> SearchDailySummaries { get; set; }
    }
}
