ALTER TABLE [dbo].[Affiliate]
    ADD CONSTRAINT [Affiliate_affid_UK] UNIQUE NONCLUSTERED ([affid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

