ALTER TABLE [dbo].[Campaign]
    ADD CONSTRAINT [Campaign_pid_UK] UNIQUE NONCLUSTERED ([pid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

