ALTER TABLE [dbo].[ItemReportingStatus]
    ADD CONSTRAINT [ItemReportingStatus_id_PK] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

