//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace AccountingBackupWeb.Models.QuickBooks
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class QuickBooksContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new QuickBooksContainer object using the connection string found in the 'QuickBooksContainer' section of the application configuration file.
        /// </summary>
        public QuickBooksContainer() : base("name=QuickBooksContainer", "QuickBooksContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QuickBooksContainer object.
        /// </summary>
        public QuickBooksContainer(string connectionString) : base(connectionString, "QuickBooksContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QuickBooksContainer object.
        /// </summary>
        public QuickBooksContainer(EntityConnection connection) : base(connection, "QuickBooksContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Entity1> Entity1
        {
            get
            {
                if ((_Entity1 == null))
                {
                    _Entity1 = base.CreateObjectSet<Entity1>("Entity1");
                }
                return _Entity1;
            }
        }
        private ObjectSet<Entity1> _Entity1;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Entity2> Entity2
        {
            get
            {
                if ((_Entity2 == null))
                {
                    _Entity2 = base.CreateObjectSet<Entity2>("Entity2");
                }
                return _Entity2;
            }
        }
        private ObjectSet<Entity2> _Entity2;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Entity1 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEntity1(Entity1 entity1)
        {
            base.AddObject("Entity1", entity1);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Entity2 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEntity2(Entity2 entity2)
        {
            base.AddObject("Entity2", entity2);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuickBooks", Name="Entity1")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Entity1 : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Entity1 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="property1">Initial value of the Property1 property.</param>
        /// <param name="bitProp">Initial value of the BitProp property.</param>
        public static Entity1 CreateEntity1(global::System.Int32 id, global::System.String property1, global::System.Boolean bitProp)
        {
            Entity1 entity1 = new Entity1();
            entity1.Id = id;
            entity1.Property1 = property1;
            entity1.BitProp = bitProp;
            return entity1;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Property1
        {
            get
            {
                return _Property1;
            }
            set
            {
                OnProperty1Changing(value);
                ReportPropertyChanging("Property1");
                _Property1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Property1");
                OnProperty1Changed();
            }
        }
        private global::System.String _Property1;
        partial void OnProperty1Changing(global::System.String value);
        partial void OnProperty1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean BitProp
        {
            get
            {
                return _BitProp;
            }
            set
            {
                OnBitPropChanging(value);
                ReportPropertyChanging("BitProp");
                _BitProp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BitProp");
                OnBitPropChanged();
            }
        }
        private global::System.Boolean _BitProp;
        partial void OnBitPropChanging(global::System.Boolean value);
        partial void OnBitPropChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuickBooks", Name="Entity2")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Entity2 : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Entity2 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="doubleProp">Initial value of the DoubleProp property.</param>
        public static Entity2 CreateEntity2(global::System.Int32 id, global::System.Double doubleProp)
        {
            Entity2 entity2 = new Entity2();
            entity2.Id = id;
            entity2.DoubleProp = doubleProp;
            return entity2;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double DoubleProp
        {
            get
            {
                return _DoubleProp;
            }
            set
            {
                OnDoublePropChanging(value);
                ReportPropertyChanging("DoubleProp");
                _DoubleProp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DoubleProp");
                OnDoublePropChanged();
            }
        }
        private global::System.Double _DoubleProp;
        partial void OnDoublePropChanging(global::System.Double value);
        partial void OnDoublePropChanged();

        #endregion
    
    }

    #endregion
    
}
