//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AccountingBackupWeb.Models.DirectTrack.Schemas.Classes.XpubClassified {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/xpubClassified/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/xpubClassified/v1_0", IsNullable=false)]
    public partial class campaignResourceURL {
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/xpubClassified/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/xpubClassified/v1_0", IsNullable=false)]
    public enum listingType {
        
        /// <remarks/>
        bid,
        
        /// <remarks/>
        proposal,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/xpubClassified/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/xpubClassified/v1_0", IsNullable=false)]
    public enum listingStatus {
        
        /// <remarks/>
        Active,
        
        /// <remarks/>
        Inactive,
        
        /// <remarks/>
        Closed,
        
        /// <remarks/>
        Expired,
        
        /// <remarks/>
        Deleted,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/xpubClassified/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/xpubClassified/v1_0", IsNullable=false)]
    public partial class xpubCompanyResourceURL {
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.digitalriver.com/directtrack/api/xpubClassified/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute("allowChildEditCreatives", Namespace="http://www.digitalriver.com/directtrack/api/xpubClassified/v1_0", IsNullable=false)]
    public enum booleanInt {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/xpubClassified/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/xpubClassified/v1_0", IsNullable=false)]
    public partial class xpubClassified {
        
        private campaignResourceURL campaignResourceURLField;
        
        private string listingNameField;
        
        private listingType listingTypeField;
        
        private bool listingTypeFieldSpecified;
        
        private string listingTitleField;
        
        private listingStatus listingStatusField;
        
        private bool listingStatusFieldSpecified;
        
        private xpubCompanyResourceURL xpubCompanyResourceURLField;
        
        private string startDateField;
        
        private string endDateField;
        
        private string shortDescriptionField;
        
        private string longDescriptionField;
        
        private double impressionPayoutField;
        
        private bool impressionPayoutFieldSpecified;
        
        private double clickPayoutField;
        
        private bool clickPayoutFieldSpecified;
        
        private double leadPayoutField;
        
        private bool leadPayoutFieldSpecified;
        
        private double flatSalePayoutField;
        
        private bool flatSalePayoutFieldSpecified;
        
        private double flatSubSalePayoutField;
        
        private bool flatSubSalePayoutFieldSpecified;
        
        private double percentSalePayoutField;
        
        private bool percentSalePayoutFieldSpecified;
        
        private double percentSubSalePayoutField;
        
        private bool percentSubSalePayoutFieldSpecified;
        
        private booleanInt allowChildEditCreativesField;
        
        private bool allowChildEditCreativesFieldSpecified;
        
        private string locationField;
        
        /// <remarks/>
        public campaignResourceURL campaignResourceURL {
            get {
                return this.campaignResourceURLField;
            }
            set {
                this.campaignResourceURLField = value;
            }
        }
        
        /// <remarks/>
        public string listingName {
            get {
                return this.listingNameField;
            }
            set {
                this.listingNameField = value;
            }
        }
        
        /// <remarks/>
        public listingType listingType {
            get {
                return this.listingTypeField;
            }
            set {
                this.listingTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listingTypeSpecified {
            get {
                return this.listingTypeFieldSpecified;
            }
            set {
                this.listingTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string listingTitle {
            get {
                return this.listingTitleField;
            }
            set {
                this.listingTitleField = value;
            }
        }
        
        /// <remarks/>
        public listingStatus listingStatus {
            get {
                return this.listingStatusField;
            }
            set {
                this.listingStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listingStatusSpecified {
            get {
                return this.listingStatusFieldSpecified;
            }
            set {
                this.listingStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public xpubCompanyResourceURL xpubCompanyResourceURL {
            get {
                return this.xpubCompanyResourceURLField;
            }
            set {
                this.xpubCompanyResourceURLField = value;
            }
        }
        
        /// <remarks/>
        public string startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        public string shortDescription {
            get {
                return this.shortDescriptionField;
            }
            set {
                this.shortDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string longDescription {
            get {
                return this.longDescriptionField;
            }
            set {
                this.longDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public double impressionPayout {
            get {
                return this.impressionPayoutField;
            }
            set {
                this.impressionPayoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool impressionPayoutSpecified {
            get {
                return this.impressionPayoutFieldSpecified;
            }
            set {
                this.impressionPayoutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double clickPayout {
            get {
                return this.clickPayoutField;
            }
            set {
                this.clickPayoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool clickPayoutSpecified {
            get {
                return this.clickPayoutFieldSpecified;
            }
            set {
                this.clickPayoutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double leadPayout {
            get {
                return this.leadPayoutField;
            }
            set {
                this.leadPayoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool leadPayoutSpecified {
            get {
                return this.leadPayoutFieldSpecified;
            }
            set {
                this.leadPayoutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double flatSalePayout {
            get {
                return this.flatSalePayoutField;
            }
            set {
                this.flatSalePayoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool flatSalePayoutSpecified {
            get {
                return this.flatSalePayoutFieldSpecified;
            }
            set {
                this.flatSalePayoutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double flatSubSalePayout {
            get {
                return this.flatSubSalePayoutField;
            }
            set {
                this.flatSubSalePayoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool flatSubSalePayoutSpecified {
            get {
                return this.flatSubSalePayoutFieldSpecified;
            }
            set {
                this.flatSubSalePayoutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double percentSalePayout {
            get {
                return this.percentSalePayoutField;
            }
            set {
                this.percentSalePayoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool percentSalePayoutSpecified {
            get {
                return this.percentSalePayoutFieldSpecified;
            }
            set {
                this.percentSalePayoutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double percentSubSalePayout {
            get {
                return this.percentSubSalePayoutField;
            }
            set {
                this.percentSubSalePayoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool percentSubSalePayoutSpecified {
            get {
                return this.percentSubSalePayoutFieldSpecified;
            }
            set {
                this.percentSubSalePayoutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public booleanInt allowChildEditCreatives {
            get {
                return this.allowChildEditCreativesField;
            }
            set {
                this.allowChildEditCreativesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool allowChildEditCreativesSpecified {
            get {
                return this.allowChildEditCreativesFieldSpecified;
            }
            set {
                this.allowChildEditCreativesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
}
