//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AccountingBackupWeb.Models.DirectTrack.Schemas.Classes.XpubRequest {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/xpubRequest/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/xpubRequest/v1_0", IsNullable=false)]
    public enum approvalStatus {
        
        /// <remarks/>
        approved,
        
        /// <remarks/>
        denied,
        
        /// <remarks/>
        pending,
        
        /// <remarks/>
        completed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/xpubRequest/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/xpubRequest/v1_0", IsNullable=false)]
    public partial class childCompanyResourceURL {
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/xpubRequest/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/xpubRequest/v1_0", IsNullable=false)]
    public partial class offerResourceURL {
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/xpubRequest/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/xpubRequest/v1_0", IsNullable=false)]
    public partial class affiliatePayout {
        
        private double perClickPayoutField;
        
        private bool perClickPayoutFieldSpecified;
        
        private double perLeadPayoutField;
        
        private bool perLeadPayoutFieldSpecified;
        
        private double perSalePayoutField;
        
        private bool perSalePayoutFieldSpecified;
        
        private double subPerSalePayoutField;
        
        private bool subPerSalePayoutFieldSpecified;
        
        private double flatPerSalePayoutField;
        
        private bool flatPerSalePayoutFieldSpecified;
        
        private double flatSubPerSalePayoutField;
        
        private bool flatSubPerSalePayoutFieldSpecified;
        
        private double perImpressionPayoutField;
        
        private bool perImpressionPayoutFieldSpecified;
        
        /// <remarks/>
        public double perClickPayout {
            get {
                return this.perClickPayoutField;
            }
            set {
                this.perClickPayoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool perClickPayoutSpecified {
            get {
                return this.perClickPayoutFieldSpecified;
            }
            set {
                this.perClickPayoutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double perLeadPayout {
            get {
                return this.perLeadPayoutField;
            }
            set {
                this.perLeadPayoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool perLeadPayoutSpecified {
            get {
                return this.perLeadPayoutFieldSpecified;
            }
            set {
                this.perLeadPayoutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double perSalePayout {
            get {
                return this.perSalePayoutField;
            }
            set {
                this.perSalePayoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool perSalePayoutSpecified {
            get {
                return this.perSalePayoutFieldSpecified;
            }
            set {
                this.perSalePayoutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double subPerSalePayout {
            get {
                return this.subPerSalePayoutField;
            }
            set {
                this.subPerSalePayoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subPerSalePayoutSpecified {
            get {
                return this.subPerSalePayoutFieldSpecified;
            }
            set {
                this.subPerSalePayoutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double flatPerSalePayout {
            get {
                return this.flatPerSalePayoutField;
            }
            set {
                this.flatPerSalePayoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool flatPerSalePayoutSpecified {
            get {
                return this.flatPerSalePayoutFieldSpecified;
            }
            set {
                this.flatPerSalePayoutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double flatSubPerSalePayout {
            get {
                return this.flatSubPerSalePayoutField;
            }
            set {
                this.flatSubPerSalePayoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool flatSubPerSalePayoutSpecified {
            get {
                return this.flatSubPerSalePayoutFieldSpecified;
            }
            set {
                this.flatSubPerSalePayoutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double perImpressionPayout {
            get {
                return this.perImpressionPayoutField;
            }
            set {
                this.perImpressionPayoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool perImpressionPayoutSpecified {
            get {
                return this.perImpressionPayoutFieldSpecified;
            }
            set {
                this.perImpressionPayoutFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/xpubRequest/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/xpubRequest/v1_0", IsNullable=false)]
    public partial class xpubRequest {
        
        private childCompanyResourceURL childCompanyResourceURLField;
        
        private offerResourceURL offerResourceURLField;
        
        private affiliatePayout affiliatePayoutField;
        
        private approvalStatus approvalStatusField;
        
        private string locationField;
        
        /// <remarks/>
        public childCompanyResourceURL childCompanyResourceURL {
            get {
                return this.childCompanyResourceURLField;
            }
            set {
                this.childCompanyResourceURLField = value;
            }
        }
        
        /// <remarks/>
        public offerResourceURL offerResourceURL {
            get {
                return this.offerResourceURLField;
            }
            set {
                this.offerResourceURLField = value;
            }
        }
        
        /// <remarks/>
        public affiliatePayout affiliatePayout {
            get {
                return this.affiliatePayoutField;
            }
            set {
                this.affiliatePayoutField = value;
            }
        }
        
        /// <remarks/>
        public approvalStatus approvalStatus {
            get {
                return this.approvalStatusField;
            }
            set {
                this.approvalStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
}
