// <auto-generated />
namespace DirectAgents.Domain.MigrationsTD
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ExtendPrimaryKeyRokuSummary : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExtendPrimaryKeyRokuSummary));
        
        string IMigrationMetadata.Id
        {
            get { return "202006021113506_ExtendPrimaryKeyRokuSummary"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
