//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AccountingBackupWeb.Models.DirectTrack.Schemas.Classes.Affiliate {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute("outsideNA", Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0", IsNullable=false)]
    public enum booleanInt {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0", IsNullable=false)]
    public partial class referredBy {
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0", IsNullable=false)]
    public enum status {
        
        /// <remarks/>
        approved,
        
        /// <remarks/>
        inactive,
        
        /// <remarks/>
        denied,
        
        /// <remarks/>
        pending,
        
        /// <remarks/>
        terminated,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0", IsNullable=false)]
    public enum approval {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Sales/Leads Only")]
        SalesLeadsOnly,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Sales/Leads and Clicks")]
        SalesLeadsandClicks,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0", IsNullable=false)]
    public partial class website {
        
        private uint idField;
        
        private bool idFieldSpecified;
        
        private string urlField;
        
        private booleanInt approvedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public booleanInt approved {
            get {
                return this.approvedField;
            }
            set {
                this.approvedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0", IsNullable=false)]
    public partial class affiliateWebsites {
        
        private website[] websiteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("website")]
        public website[] website {
            get {
                return this.websiteField;
            }
            set {
                this.websiteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0", IsNullable=false)]
    public partial class commission {
        
        private uint idField;
        
        private bool idFieldSpecified;
        
        private string effectiveDateField;
        
        private string percentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string effectiveDate {
            get {
                return this.effectiveDateField;
            }
            set {
                this.effectiveDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string percent {
            get {
                return this.percentField;
            }
            set {
                this.percentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0", IsNullable=false)]
    public partial class blanketCommissions {
        
        private commission[] commissionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("commission")]
        public commission[] commission {
            get {
                return this.commissionField;
            }
            set {
                this.commissionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0", IsNullable=false)]
    public partial class resourceURL {
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0", IsNullable=false)]
    public partial class affiliateGroups {
        
        private resourceURL[] resourceURLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resourceURL")]
        public resourceURL[] resourceURL {
            get {
                return this.resourceURLField;
            }
            set {
                this.resourceURLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0", IsNullable=false)]
    public partial class directDepositDetails {
        
        private string bankNameField;
        
        private string accountNameField;
        
        private string bankAccountNumberField;
        
        private string iBANField;
        
        private string routingNumberField;
        
        private string bankAddressField;
        
        private string bankAddress2Field;
        
        private string bankCityField;
        
        private string bankStateField;
        
        private string bankZipField;
        
        private string bankCountryField;
        
        /// <remarks/>
        public string bankName {
            get {
                return this.bankNameField;
            }
            set {
                this.bankNameField = value;
            }
        }
        
        /// <remarks/>
        public string accountName {
            get {
                return this.accountNameField;
            }
            set {
                this.accountNameField = value;
            }
        }
        
        /// <remarks/>
        public string bankAccountNumber {
            get {
                return this.bankAccountNumberField;
            }
            set {
                this.bankAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string IBAN {
            get {
                return this.iBANField;
            }
            set {
                this.iBANField = value;
            }
        }
        
        /// <remarks/>
        public string routingNumber {
            get {
                return this.routingNumberField;
            }
            set {
                this.routingNumberField = value;
            }
        }
        
        /// <remarks/>
        public string bankAddress {
            get {
                return this.bankAddressField;
            }
            set {
                this.bankAddressField = value;
            }
        }
        
        /// <remarks/>
        public string bankAddress2 {
            get {
                return this.bankAddress2Field;
            }
            set {
                this.bankAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string bankCity {
            get {
                return this.bankCityField;
            }
            set {
                this.bankCityField = value;
            }
        }
        
        /// <remarks/>
        public string bankState {
            get {
                return this.bankStateField;
            }
            set {
                this.bankStateField = value;
            }
        }
        
        /// <remarks/>
        public string bankZip {
            get {
                return this.bankZipField;
            }
            set {
                this.bankZipField = value;
            }
        }
        
        /// <remarks/>
        public string bankCountry {
            get {
                return this.bankCountryField;
            }
            set {
                this.bankCountryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0", IsNullable=false)]
    public partial class wireTransferDetails {
        
        private string bankNameField;
        
        private string accountNameField;
        
        private string bankAccountNumberField;
        
        private string iBANField;
        
        private string routingNumberField;
        
        private string bankAddressField;
        
        private string bankAddress2Field;
        
        private string bankCityField;
        
        private string bankStateField;
        
        private string bankZipField;
        
        private string bankCountryField;
        
        private string intBankCodeField;
        
        private string intBankAddressField;
        
        private string intBankAddress2Field;
        
        private string intBankAddress3Field;
        
        private string instructionsField;
        
        private string wireCurrencyField;
        
        /// <remarks/>
        public string bankName {
            get {
                return this.bankNameField;
            }
            set {
                this.bankNameField = value;
            }
        }
        
        /// <remarks/>
        public string accountName {
            get {
                return this.accountNameField;
            }
            set {
                this.accountNameField = value;
            }
        }
        
        /// <remarks/>
        public string bankAccountNumber {
            get {
                return this.bankAccountNumberField;
            }
            set {
                this.bankAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string IBAN {
            get {
                return this.iBANField;
            }
            set {
                this.iBANField = value;
            }
        }
        
        /// <remarks/>
        public string routingNumber {
            get {
                return this.routingNumberField;
            }
            set {
                this.routingNumberField = value;
            }
        }
        
        /// <remarks/>
        public string bankAddress {
            get {
                return this.bankAddressField;
            }
            set {
                this.bankAddressField = value;
            }
        }
        
        /// <remarks/>
        public string bankAddress2 {
            get {
                return this.bankAddress2Field;
            }
            set {
                this.bankAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string bankCity {
            get {
                return this.bankCityField;
            }
            set {
                this.bankCityField = value;
            }
        }
        
        /// <remarks/>
        public string bankState {
            get {
                return this.bankStateField;
            }
            set {
                this.bankStateField = value;
            }
        }
        
        /// <remarks/>
        public string bankZip {
            get {
                return this.bankZipField;
            }
            set {
                this.bankZipField = value;
            }
        }
        
        /// <remarks/>
        public string bankCountry {
            get {
                return this.bankCountryField;
            }
            set {
                this.bankCountryField = value;
            }
        }
        
        /// <remarks/>
        public string intBankCode {
            get {
                return this.intBankCodeField;
            }
            set {
                this.intBankCodeField = value;
            }
        }
        
        /// <remarks/>
        public string intBankAddress {
            get {
                return this.intBankAddressField;
            }
            set {
                this.intBankAddressField = value;
            }
        }
        
        /// <remarks/>
        public string intBankAddress2 {
            get {
                return this.intBankAddress2Field;
            }
            set {
                this.intBankAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string intBankAddress3 {
            get {
                return this.intBankAddress3Field;
            }
            set {
                this.intBankAddress3Field = value;
            }
        }
        
        /// <remarks/>
        public string instructions {
            get {
                return this.instructionsField;
            }
            set {
                this.instructionsField = value;
            }
        }
        
        /// <remarks/>
        public string wireCurrency {
            get {
                return this.wireCurrencyField;
            }
            set {
                this.wireCurrencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0", IsNullable=false)]
    public enum paymentFrequency {
        
        /// <remarks/>
        monthly,
        
        /// <remarks/>
        weekly,
        
        /// <remarks/>
        biweekly,
        
        /// <remarks/>
        quarterly,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0", IsNullable=false)]
    public enum paymentTo {
        
        /// <remarks/>
        personal,
        
        /// <remarks/>
        company,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0", IsNullable=false)]
    public enum paymentMethod {
        
        /// <remarks/>
        check,
        
        /// <remarks/>
        paypal,
        
        /// <remarks/>
        directDeposit,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0", IsNullable=false)]
    public enum paymentStatus {
        
        /// <remarks/>
        Paid,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Under Review")]
        UnderReview,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("No W9")]
        NoW9,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Pending First Payment")]
        PendingFirstPayment,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Pending Payment")]
        PendingPayment,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Approved for First Payment")]
        ApprovedforFirstPayment,
        
        /// <remarks/>
        Terminated,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Company Account - Not Paid")]
        CompanyAccountNotPaid,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Export To Quickbooks")]
        ExportToQuickbooks,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0", IsNullable=false)]
    public partial class customField {
        
        private uint idField;
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0", IsNullable=false)]
    public partial class customFields {
        
        private customField[] customFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("customField")]
        public customField[] customField {
            get {
                return this.customFieldField;
            }
            set {
                this.customFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/affiliate/v1_0", IsNullable=false)]
    public partial class affiliate {
        
        private string addCodeField;
        
        private string emailField;
        
        private status statusField;
        
        private bool statusFieldSpecified;
        
        private approval approvalField;
        
        private bool approvalFieldSpecified;
        
        private string passwordField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string companyField;
        
        private string addressField;
        
        private string address2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private string countryField;
        
        private booleanInt outsideNAField;
        
        private bool outsideNAFieldSpecified;
        
        private string stateOtherField;
        
        private string phoneField;
        
        private string faxField;
        
        private string ssnField;
        
        private website[] affiliateWebsitesField;
        
        private booleanInt filterWebsiteField;
        
        private bool filterWebsiteFieldSpecified;
        
        private string category1Field;
        
        private string category2Field;
        
        private string category3Field;
        
        private commission[] blanketCommissionsField;
        
        private string internalCommentsField;
        
        private string approvalNotesField;
        
        private booleanInt watchMeField;
        
        private bool watchMeFieldSpecified;
        
        private referredBy referredByField;
        
        private string agreedTermsField;
        
        private booleanInt w9OnFileField;
        
        private bool w9OnFileFieldSpecified;
        
        private string signUpDateField;
        
        private string ipAddressField;
        
        private string siteTypeField;
        
        private string siteDescriptionField;
        
        private uint siteViewsField;
        
        private bool siteViewsFieldSpecified;
        
        private resourceURL[] affiliateGroupsField;
        
        private string languageContentField;
        
        private booleanInt globalPopField;
        
        private bool globalPopFieldSpecified;
        
        private booleanInt hideAdservingField;
        
        private bool hideAdservingFieldSpecified;
        
        private booleanInt allowThirdPartyUploadField;
        
        private bool allowThirdPartyUploadFieldSpecified;
        
        private booleanInt sendApprovalEmailField;
        
        private bool sendApprovalEmailFieldSpecified;
        
        private string redirectURLField;
        
        private booleanInt datafeedApprovalField;
        
        private bool datafeedApprovalFieldSpecified;
        
        private string paypalEmailField;
        
        private short paymentThresholdField;
        
        private bool paymentThresholdFieldSpecified;
        
        private paymentFrequency paymentFrequencyField;
        
        private bool paymentFrequencyFieldSpecified;
        
        private paymentTo paymentToField;
        
        private bool paymentToFieldSpecified;
        
        private paymentMethod paymentMethodField;
        
        private bool paymentMethodFieldSpecified;
        
        private paymentStatus paymentStatusField;
        
        private bool paymentStatusFieldSpecified;
        
        private booleanInt form1099RequiredField;
        
        private bool form1099RequiredFieldSpecified;
        
        private booleanInt taxIDIsSSNField;
        
        private bool taxIDIsSSNFieldSpecified;
        
        private string currencyField;
        
        private directDepositDetails directDepositDetailsField;
        
        private wireTransferDetails wireTransferDetailsField;
        
        private string terminateAffiliateReasonField;
        
        private booleanInt resetPasswordField;
        
        private bool resetPasswordFieldSpecified;
        
        private booleanInt manualEmailField;
        
        private bool manualEmailFieldSpecified;
        
        private booleanInt updatesNotificationField;
        
        private bool updatesNotificationFieldSpecified;
        
        private uint paymentNotificationField;
        
        private bool paymentNotificationFieldSpecified;
        
        private booleanInt conversionNotificationField;
        
        private bool conversionNotificationFieldSpecified;
        
        private customField[] customFieldsField;
        
        private uint accessIDField;
        
        private bool accessIDFieldSpecified;
        
        private string locationField;
        
        /// <remarks/>
        public string addCode {
            get {
                return this.addCodeField;
            }
            set {
                this.addCodeField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public status status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public approval approval {
            get {
                return this.approvalField;
            }
            set {
                this.approvalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool approvalSpecified {
            get {
                return this.approvalFieldSpecified;
            }
            set {
                this.approvalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public booleanInt outsideNA {
            get {
                return this.outsideNAField;
            }
            set {
                this.outsideNAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool outsideNASpecified {
            get {
                return this.outsideNAFieldSpecified;
            }
            set {
                this.outsideNAFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string stateOther {
            get {
                return this.stateOtherField;
            }
            set {
                this.stateOtherField = value;
            }
        }
        
        /// <remarks/>
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        public string ssn {
            get {
                return this.ssnField;
            }
            set {
                this.ssnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("website", IsNullable=false)]
        public website[] affiliateWebsites {
            get {
                return this.affiliateWebsitesField;
            }
            set {
                this.affiliateWebsitesField = value;
            }
        }
        
        /// <remarks/>
        public booleanInt filterWebsite {
            get {
                return this.filterWebsiteField;
            }
            set {
                this.filterWebsiteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool filterWebsiteSpecified {
            get {
                return this.filterWebsiteFieldSpecified;
            }
            set {
                this.filterWebsiteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string category1 {
            get {
                return this.category1Field;
            }
            set {
                this.category1Field = value;
            }
        }
        
        /// <remarks/>
        public string category2 {
            get {
                return this.category2Field;
            }
            set {
                this.category2Field = value;
            }
        }
        
        /// <remarks/>
        public string category3 {
            get {
                return this.category3Field;
            }
            set {
                this.category3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("commission", IsNullable=false)]
        public commission[] blanketCommissions {
            get {
                return this.blanketCommissionsField;
            }
            set {
                this.blanketCommissionsField = value;
            }
        }
        
        /// <remarks/>
        public string internalComments {
            get {
                return this.internalCommentsField;
            }
            set {
                this.internalCommentsField = value;
            }
        }
        
        /// <remarks/>
        public string approvalNotes {
            get {
                return this.approvalNotesField;
            }
            set {
                this.approvalNotesField = value;
            }
        }
        
        /// <remarks/>
        public booleanInt watchMe {
            get {
                return this.watchMeField;
            }
            set {
                this.watchMeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool watchMeSpecified {
            get {
                return this.watchMeFieldSpecified;
            }
            set {
                this.watchMeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public referredBy referredBy {
            get {
                return this.referredByField;
            }
            set {
                this.referredByField = value;
            }
        }
        
        /// <remarks/>
        public string agreedTerms {
            get {
                return this.agreedTermsField;
            }
            set {
                this.agreedTermsField = value;
            }
        }
        
        /// <remarks/>
        public booleanInt w9OnFile {
            get {
                return this.w9OnFileField;
            }
            set {
                this.w9OnFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool w9OnFileSpecified {
            get {
                return this.w9OnFileFieldSpecified;
            }
            set {
                this.w9OnFileFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string signUpDate {
            get {
                return this.signUpDateField;
            }
            set {
                this.signUpDateField = value;
            }
        }
        
        /// <remarks/>
        public string ipAddress {
            get {
                return this.ipAddressField;
            }
            set {
                this.ipAddressField = value;
            }
        }
        
        /// <remarks/>
        public string siteType {
            get {
                return this.siteTypeField;
            }
            set {
                this.siteTypeField = value;
            }
        }
        
        /// <remarks/>
        public string siteDescription {
            get {
                return this.siteDescriptionField;
            }
            set {
                this.siteDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public uint siteViews {
            get {
                return this.siteViewsField;
            }
            set {
                this.siteViewsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool siteViewsSpecified {
            get {
                return this.siteViewsFieldSpecified;
            }
            set {
                this.siteViewsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("resourceURL", IsNullable=false)]
        public resourceURL[] affiliateGroups {
            get {
                return this.affiliateGroupsField;
            }
            set {
                this.affiliateGroupsField = value;
            }
        }
        
        /// <remarks/>
        public string languageContent {
            get {
                return this.languageContentField;
            }
            set {
                this.languageContentField = value;
            }
        }
        
        /// <remarks/>
        public booleanInt globalPop {
            get {
                return this.globalPopField;
            }
            set {
                this.globalPopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool globalPopSpecified {
            get {
                return this.globalPopFieldSpecified;
            }
            set {
                this.globalPopFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public booleanInt hideAdserving {
            get {
                return this.hideAdservingField;
            }
            set {
                this.hideAdservingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hideAdservingSpecified {
            get {
                return this.hideAdservingFieldSpecified;
            }
            set {
                this.hideAdservingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public booleanInt allowThirdPartyUpload {
            get {
                return this.allowThirdPartyUploadField;
            }
            set {
                this.allowThirdPartyUploadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool allowThirdPartyUploadSpecified {
            get {
                return this.allowThirdPartyUploadFieldSpecified;
            }
            set {
                this.allowThirdPartyUploadFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public booleanInt sendApprovalEmail {
            get {
                return this.sendApprovalEmailField;
            }
            set {
                this.sendApprovalEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sendApprovalEmailSpecified {
            get {
                return this.sendApprovalEmailFieldSpecified;
            }
            set {
                this.sendApprovalEmailFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string redirectURL {
            get {
                return this.redirectURLField;
            }
            set {
                this.redirectURLField = value;
            }
        }
        
        /// <remarks/>
        public booleanInt datafeedApproval {
            get {
                return this.datafeedApprovalField;
            }
            set {
                this.datafeedApprovalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datafeedApprovalSpecified {
            get {
                return this.datafeedApprovalFieldSpecified;
            }
            set {
                this.datafeedApprovalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string paypalEmail {
            get {
                return this.paypalEmailField;
            }
            set {
                this.paypalEmailField = value;
            }
        }
        
        /// <remarks/>
        public short paymentThreshold {
            get {
                return this.paymentThresholdField;
            }
            set {
                this.paymentThresholdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool paymentThresholdSpecified {
            get {
                return this.paymentThresholdFieldSpecified;
            }
            set {
                this.paymentThresholdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public paymentFrequency paymentFrequency {
            get {
                return this.paymentFrequencyField;
            }
            set {
                this.paymentFrequencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool paymentFrequencySpecified {
            get {
                return this.paymentFrequencyFieldSpecified;
            }
            set {
                this.paymentFrequencyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public paymentTo paymentTo {
            get {
                return this.paymentToField;
            }
            set {
                this.paymentToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool paymentToSpecified {
            get {
                return this.paymentToFieldSpecified;
            }
            set {
                this.paymentToFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public paymentMethod paymentMethod {
            get {
                return this.paymentMethodField;
            }
            set {
                this.paymentMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool paymentMethodSpecified {
            get {
                return this.paymentMethodFieldSpecified;
            }
            set {
                this.paymentMethodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public paymentStatus paymentStatus {
            get {
                return this.paymentStatusField;
            }
            set {
                this.paymentStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool paymentStatusSpecified {
            get {
                return this.paymentStatusFieldSpecified;
            }
            set {
                this.paymentStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public booleanInt form1099Required {
            get {
                return this.form1099RequiredField;
            }
            set {
                this.form1099RequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool form1099RequiredSpecified {
            get {
                return this.form1099RequiredFieldSpecified;
            }
            set {
                this.form1099RequiredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public booleanInt taxIDIsSSN {
            get {
                return this.taxIDIsSSNField;
            }
            set {
                this.taxIDIsSSNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool taxIDIsSSNSpecified {
            get {
                return this.taxIDIsSSNFieldSpecified;
            }
            set {
                this.taxIDIsSSNFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public directDepositDetails directDepositDetails {
            get {
                return this.directDepositDetailsField;
            }
            set {
                this.directDepositDetailsField = value;
            }
        }
        
        /// <remarks/>
        public wireTransferDetails wireTransferDetails {
            get {
                return this.wireTransferDetailsField;
            }
            set {
                this.wireTransferDetailsField = value;
            }
        }
        
        /// <remarks/>
        public string terminateAffiliateReason {
            get {
                return this.terminateAffiliateReasonField;
            }
            set {
                this.terminateAffiliateReasonField = value;
            }
        }
        
        /// <remarks/>
        public booleanInt resetPassword {
            get {
                return this.resetPasswordField;
            }
            set {
                this.resetPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resetPasswordSpecified {
            get {
                return this.resetPasswordFieldSpecified;
            }
            set {
                this.resetPasswordFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public booleanInt manualEmail {
            get {
                return this.manualEmailField;
            }
            set {
                this.manualEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool manualEmailSpecified {
            get {
                return this.manualEmailFieldSpecified;
            }
            set {
                this.manualEmailFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public booleanInt updatesNotification {
            get {
                return this.updatesNotificationField;
            }
            set {
                this.updatesNotificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updatesNotificationSpecified {
            get {
                return this.updatesNotificationFieldSpecified;
            }
            set {
                this.updatesNotificationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint paymentNotification {
            get {
                return this.paymentNotificationField;
            }
            set {
                this.paymentNotificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool paymentNotificationSpecified {
            get {
                return this.paymentNotificationFieldSpecified;
            }
            set {
                this.paymentNotificationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public booleanInt conversionNotification {
            get {
                return this.conversionNotificationField;
            }
            set {
                this.conversionNotificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool conversionNotificationSpecified {
            get {
                return this.conversionNotificationFieldSpecified;
            }
            set {
                this.conversionNotificationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("customField", IsNullable=false)]
        public customField[] customFields {
            get {
                return this.customFieldsField;
            }
            set {
                this.customFieldsField = value;
            }
        }
        
        /// <remarks/>
        public uint accessID {
            get {
                return this.accessIDField;
            }
            set {
                this.accessIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool accessIDSpecified {
            get {
                return this.accessIDFieldSpecified;
            }
            set {
                this.accessIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
}
