//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AccountingBackupWeb.Models.DirectTrack.Schemas.Classes.Payout {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/payout/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/payout/v1_0", IsNullable=false)]
    public enum payoutType {
        
        /// <remarks/>
        campaign,
        
        /// <remarks/>
        affiliate,
        
        /// <remarks/>
        product,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("view-through campaign")]
        viewthroughcampaign,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("view-through affiliate")]
        viewthroughaffiliate,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/payout/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/payout/v1_0", IsNullable=false)]
    public partial class campaignResourceURL {
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/payout/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/payout/v1_0", IsNullable=false)]
    public partial class productResourceURL {
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/payout/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/payout/v1_0", IsNullable=false)]
    public partial class affiliate {
        
        private booleanInt allAffiliatesField;
        
        private bool allAffiliatesFieldSpecified;
        
        private string affiliateResourceURLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public booleanInt allAffiliates {
            get {
                return this.allAffiliatesField;
            }
            set {
                this.allAffiliatesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool allAffiliatesSpecified {
            get {
                return this.allAffiliatesFieldSpecified;
            }
            set {
                this.allAffiliatesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string affiliateResourceURL {
            get {
                return this.affiliateResourceURLField;
            }
            set {
                this.affiliateResourceURLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.digitalriver.com/directtrack/api/payout/v1_0")]
    public enum booleanInt {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/payout/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/payout/v1_0", IsNullable=false)]
    public partial class payout {
        
        private payoutType payoutTypeField;
        
        private campaignResourceURL campaignResourceURLField;
        
        private affiliate affiliateField;
        
        private decimal impressionField;
        
        private bool impressionFieldSpecified;
        
        private decimal clickField;
        
        private bool clickFieldSpecified;
        
        private decimal leadField;
        
        private bool leadFieldSpecified;
        
        private decimal percentSaleField;
        
        private bool percentSaleFieldSpecified;
        
        private decimal flatSaleField;
        
        private bool flatSaleFieldSpecified;
        
        private decimal percentSubSaleField;
        
        private bool percentSubSaleFieldSpecified;
        
        private decimal flatSubSaleField;
        
        private bool flatSubSaleFieldSpecified;
        
        private string effectiveDateField;
        
        private string modifyDateField;
        
        private productResourceURL productResourceURLField;
        
        private string currencyField;
        
        private string locationField;
        
        /// <remarks/>
        public payoutType payoutType {
            get {
                return this.payoutTypeField;
            }
            set {
                this.payoutTypeField = value;
            }
        }
        
        /// <remarks/>
        public campaignResourceURL campaignResourceURL {
            get {
                return this.campaignResourceURLField;
            }
            set {
                this.campaignResourceURLField = value;
            }
        }
        
        /// <remarks/>
        public affiliate affiliate {
            get {
                return this.affiliateField;
            }
            set {
                this.affiliateField = value;
            }
        }
        
        /// <remarks/>
        public decimal impression {
            get {
                return this.impressionField;
            }
            set {
                this.impressionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool impressionSpecified {
            get {
                return this.impressionFieldSpecified;
            }
            set {
                this.impressionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal click {
            get {
                return this.clickField;
            }
            set {
                this.clickField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool clickSpecified {
            get {
                return this.clickFieldSpecified;
            }
            set {
                this.clickFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal lead {
            get {
                return this.leadField;
            }
            set {
                this.leadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool leadSpecified {
            get {
                return this.leadFieldSpecified;
            }
            set {
                this.leadFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal percentSale {
            get {
                return this.percentSaleField;
            }
            set {
                this.percentSaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool percentSaleSpecified {
            get {
                return this.percentSaleFieldSpecified;
            }
            set {
                this.percentSaleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal flatSale {
            get {
                return this.flatSaleField;
            }
            set {
                this.flatSaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool flatSaleSpecified {
            get {
                return this.flatSaleFieldSpecified;
            }
            set {
                this.flatSaleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal percentSubSale {
            get {
                return this.percentSubSaleField;
            }
            set {
                this.percentSubSaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool percentSubSaleSpecified {
            get {
                return this.percentSubSaleFieldSpecified;
            }
            set {
                this.percentSubSaleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal flatSubSale {
            get {
                return this.flatSubSaleField;
            }
            set {
                this.flatSubSaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool flatSubSaleSpecified {
            get {
                return this.flatSubSaleFieldSpecified;
            }
            set {
                this.flatSubSaleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string effectiveDate {
            get {
                return this.effectiveDateField;
            }
            set {
                this.effectiveDateField = value;
            }
        }
        
        /// <remarks/>
        public string modifyDate {
            get {
                return this.modifyDateField;
            }
            set {
                this.modifyDateField = value;
            }
        }
        
        /// <remarks/>
        public productResourceURL productResourceURL {
            get {
                return this.productResourceURLField;
            }
            set {
                this.productResourceURLField = value;
            }
        }
        
        /// <remarks/>
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
}
