//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AccountingBackupWeb.Models.DirectTrack.Schemas.Classes.ProgramImpression {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/programImpression/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/programImpression/v1_0", IsNullable=false)]
    public partial class affiliateResourceURL {
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/programImpression/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/programImpression/v1_0", IsNullable=false)]
    public partial class campaignResourceURL {
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/programImpression/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/programImpression/v1_0", IsNullable=false)]
    public partial class creativeResourceURL {
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/programImpression/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/programImpression/v1_0", IsNullable=false)]
    public partial class creativeDeploymentResourceURL {
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.digitalriver.com/directtrack/api/programImpression/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute("isContextual", Namespace="http://www.digitalriver.com/directtrack/api/programImpression/v1_0", IsNullable=false)]
    public enum booleanInt {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/programImpression/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/programImpression/v1_0", IsNullable=false)]
    public partial class subIDs {
        
        private string subID1Field;
        
        private string subID2Field;
        
        private string subID3Field;
        
        private string subID4Field;
        
        private string subID5Field;
        
        /// <remarks/>
        public string subID1 {
            get {
                return this.subID1Field;
            }
            set {
                this.subID1Field = value;
            }
        }
        
        /// <remarks/>
        public string subID2 {
            get {
                return this.subID2Field;
            }
            set {
                this.subID2Field = value;
            }
        }
        
        /// <remarks/>
        public string subID3 {
            get {
                return this.subID3Field;
            }
            set {
                this.subID3Field = value;
            }
        }
        
        /// <remarks/>
        public string subID4 {
            get {
                return this.subID4Field;
            }
            set {
                this.subID4Field = value;
            }
        }
        
        /// <remarks/>
        public string subID5 {
            get {
                return this.subID5Field;
            }
            set {
                this.subID5Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/programImpression/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/programImpression/v1_0", IsNullable=false)]
    public partial class programImpression {
        
        private uint numImpressionsField;
        
        private affiliateResourceURL affiliateResourceURLField;
        
        private campaignResourceURL campaignResourceURLField;
        
        private creativeResourceURL creativeResourceURLField;
        
        private creativeDeploymentResourceURL creativeDeploymentResourceURLField;
        
        private string dateField;
        
        private subIDs subIDsField;
        
        private booleanInt isContextualField;
        
        private bool isContextualFieldSpecified;
        
        private uint landingPageIDField;
        
        private bool landingPageIDFieldSpecified;
        
        private uint poolIDField;
        
        private bool poolIDFieldSpecified;
        
        private string locationField;
        
        /// <remarks/>
        public uint numImpressions {
            get {
                return this.numImpressionsField;
            }
            set {
                this.numImpressionsField = value;
            }
        }
        
        /// <remarks/>
        public affiliateResourceURL affiliateResourceURL {
            get {
                return this.affiliateResourceURLField;
            }
            set {
                this.affiliateResourceURLField = value;
            }
        }
        
        /// <remarks/>
        public campaignResourceURL campaignResourceURL {
            get {
                return this.campaignResourceURLField;
            }
            set {
                this.campaignResourceURLField = value;
            }
        }
        
        /// <remarks/>
        public creativeResourceURL creativeResourceURL {
            get {
                return this.creativeResourceURLField;
            }
            set {
                this.creativeResourceURLField = value;
            }
        }
        
        /// <remarks/>
        public creativeDeploymentResourceURL creativeDeploymentResourceURL {
            get {
                return this.creativeDeploymentResourceURLField;
            }
            set {
                this.creativeDeploymentResourceURLField = value;
            }
        }
        
        /// <remarks/>
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public subIDs subIDs {
            get {
                return this.subIDsField;
            }
            set {
                this.subIDsField = value;
            }
        }
        
        /// <remarks/>
        public booleanInt isContextual {
            get {
                return this.isContextualField;
            }
            set {
                this.isContextualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isContextualSpecified {
            get {
                return this.isContextualFieldSpecified;
            }
            set {
                this.isContextualFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint landingPageID {
            get {
                return this.landingPageIDField;
            }
            set {
                this.landingPageIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool landingPageIDSpecified {
            get {
                return this.landingPageIDFieldSpecified;
            }
            set {
                this.landingPageIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint poolID {
            get {
                return this.poolIDField;
            }
            set {
                this.poolIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poolIDSpecified {
            get {
                return this.poolIDFieldSpecified;
            }
            set {
                this.poolIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
}
