//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AccountingBackupWeb.Models.DirectTrack.Schemas.Classes.CampaignAccessRequest {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/campaignAccessRequest/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/campaignAccessRequest/v1_0", IsNullable=false)]
    public enum requestType {
        
        /// <remarks/>
        click,
        
        /// <remarks/>
        select,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/campaignAccessRequest/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/campaignAccessRequest/v1_0", IsNullable=false)]
    public enum requestStatus {
        
        /// <remarks/>
        pending,
        
        /// <remarks/>
        denied,
        
        /// <remarks/>
        approved,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/campaignAccessRequest/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/campaignAccessRequest/v1_0", IsNullable=false)]
    public partial class campaignResourceURL {
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/campaignAccessRequest/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/campaignAccessRequest/v1_0", IsNullable=false)]
    public partial class affiliateResourceURL {
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/campaignAccessRequest/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/campaignAccessRequest/v1_0", IsNullable=false)]
    public partial class campaignAccessRequest {
        
        private requestType requestTypeField;
        
        private bool requestTypeFieldSpecified;
        
        private affiliateResourceURL affiliateResourceURLField;
        
        private requestStatus requestStatusField;
        
        private bool requestStatusFieldSpecified;
        
        private campaignResourceURL campaignResourceURLField;
        
        private string dateRequestedField;
        
        private string commentToAffiliateField;
        
        private string locationField;
        
        /// <remarks/>
        public requestType requestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool requestTypeSpecified {
            get {
                return this.requestTypeFieldSpecified;
            }
            set {
                this.requestTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public affiliateResourceURL affiliateResourceURL {
            get {
                return this.affiliateResourceURLField;
            }
            set {
                this.affiliateResourceURLField = value;
            }
        }
        
        /// <remarks/>
        public requestStatus requestStatus {
            get {
                return this.requestStatusField;
            }
            set {
                this.requestStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool requestStatusSpecified {
            get {
                return this.requestStatusFieldSpecified;
            }
            set {
                this.requestStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public campaignResourceURL campaignResourceURL {
            get {
                return this.campaignResourceURLField;
            }
            set {
                this.campaignResourceURLField = value;
            }
        }
        
        /// <remarks/>
        public string dateRequested {
            get {
                return this.dateRequestedField;
            }
            set {
                this.dateRequestedField = value;
            }
        }
        
        /// <remarks/>
        public string commentToAffiliate {
            get {
                return this.commentToAffiliateField;
            }
            set {
                this.commentToAffiliateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
}
