CREATE TABLE [dbo].[Affiliate] (
    [id]                 INT           IDENTITY (1, 1) NOT NULL,
    [name]               VARCHAR (255) NOT NULL,
    [media_buyer_id]     INT           NOT NULL,
    [affid]              INT           NOT NULL,
    [currency_id]        INT           NOT NULL,
    [email]              VARCHAR (100) NOT NULL,
    [add_code]           VARCHAR (100) NOT NULL,
    [net_term_type_id]   INT           NULL,
    [payment_method_id]  INT           NOT NULL,
    [name2]              AS            ((([name]+' (')+[add_code])+')'),
    [date_created]       DATETIME      NULL,
    [date_modified]      DATETIME      NULL,
    [tracking_system_id] INT           NULL,
    [external_id]        INT           NULL,
    [status]             VARCHAR (50)  NULL,
    [margin_exempt]      BIT           CONSTRAINT [DF_Affiliate_margin_exempt] DEFAULT ((0)) NOT NULL,
    [payment_on_hold] VARCHAR(100) NULL, 
    CONSTRAINT [Affiliate_id_PK] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [Affiliate_AffiliatePaymentMethod_id_FK_AffiliatePaymentMethod_id_PK] FOREIGN KEY ([payment_method_id]) REFERENCES [dbo].[AffiliatePaymentMethod] ([id]),
    CONSTRAINT [Affiliate_Currency_id_FK_Currency_id_PK] FOREIGN KEY ([currency_id]) REFERENCES [dbo].[Currency] ([id]),
    CONSTRAINT [Affiliate_MediaBuyer_id_FK_MediaBuyer_id_PK] FOREIGN KEY ([media_buyer_id]) REFERENCES [dbo].[MediaBuyer] ([id]),
    CONSTRAINT [Affiliate_NetTermType_id_FK_NetTermType_id_PK] FOREIGN KEY ([net_term_type_id]) REFERENCES [dbo].[NetTermType] ([id]),
    CONSTRAINT [affiliate_tracking_system_fk] FOREIGN KEY ([tracking_system_id]) REFERENCES [dbo].[TrackingSystem] ([id]),
    CONSTRAINT [Affiliate_affid_UK] UNIQUE NONCLUSTERED ([affid] ASC)
);

