// <auto-generated />
namespace ApiClient.Models.DirectTrack.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class leads : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(leads));
        
        string IMigrationMetadata.Id
        {
            get { return "201210151959583_leads"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
