#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EomApp1.UtilForms.CopyAdvertisersFromLastMonth
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DADatabaseR1")]
	public partial class DecDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCampaign(Dec.Campaign instance);
    partial void UpdateCampaign(Dec.Campaign instance);
    partial void DeleteCampaign(Dec.Campaign instance);
    partial void InsertAdvertiser(Dec.Advertiser instance);
    partial void UpdateAdvertiser(Dec.Advertiser instance);
    partial void DeleteAdvertiser(Dec.Advertiser instance);
    #endregion
		
		public DecDataContext() : 
				base(global::EomApp1.Properties.Settings.Default.DADatabaseR1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DecDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DecDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DecDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DecDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Dec.Campaign> Campaigns
		{
			get
			{
				return this.GetTable<Dec.Campaign>();
			}
		}
		
		public System.Data.Linq.Table<Dec.Advertiser> Advertisers
		{
			get
			{
				return this.GetTable<Dec.Advertiser>();
			}
		}
	}
}
namespace Dec
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Campaign")]
	public partial class Campaign : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _account_manager_id;
		
		private int _campaign_status_id;
		
		private int _ad_manager_id;
		
		private int _advertiser_id;
		
		private int _pid;
		
		private string _campaign_name;
		
		private string _campaign_type;
		
		private System.Nullable<System.DateTime> _modified;
		
		private System.Nullable<System.DateTime> _created;
		
		private EntityRef<Advertiser> _Advertiser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onaccount_manager_idChanging(int value);
    partial void Onaccount_manager_idChanged();
    partial void Oncampaign_status_idChanging(int value);
    partial void Oncampaign_status_idChanged();
    partial void Onad_manager_idChanging(int value);
    partial void Onad_manager_idChanged();
    partial void Onadvertiser_idChanging(int value);
    partial void Onadvertiser_idChanged();
    partial void OnpidChanging(int value);
    partial void OnpidChanged();
    partial void Oncampaign_nameChanging(string value);
    partial void Oncampaign_nameChanged();
    partial void Oncampaign_typeChanging(string value);
    partial void Oncampaign_typeChanged();
    partial void OnmodifiedChanging(System.Nullable<System.DateTime> value);
    partial void OnmodifiedChanged();
    partial void OncreatedChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedChanged();
    #endregion
		
		public Campaign()
		{
			this._Advertiser = default(EntityRef<Advertiser>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_account_manager_id", DbType="Int NOT NULL")]
		public int account_manager_id
		{
			get
			{
				return this._account_manager_id;
			}
			set
			{
				if ((this._account_manager_id != value))
				{
					this.Onaccount_manager_idChanging(value);
					this.SendPropertyChanging();
					this._account_manager_id = value;
					this.SendPropertyChanged("account_manager_id");
					this.Onaccount_manager_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campaign_status_id", DbType="Int NOT NULL")]
		public int campaign_status_id
		{
			get
			{
				return this._campaign_status_id;
			}
			set
			{
				if ((this._campaign_status_id != value))
				{
					this.Oncampaign_status_idChanging(value);
					this.SendPropertyChanging();
					this._campaign_status_id = value;
					this.SendPropertyChanged("campaign_status_id");
					this.Oncampaign_status_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad_manager_id", DbType="Int NOT NULL")]
		public int ad_manager_id
		{
			get
			{
				return this._ad_manager_id;
			}
			set
			{
				if ((this._ad_manager_id != value))
				{
					this.Onad_manager_idChanging(value);
					this.SendPropertyChanging();
					this._ad_manager_id = value;
					this.SendPropertyChanged("ad_manager_id");
					this.Onad_manager_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_advertiser_id", DbType="Int NOT NULL")]
		public int advertiser_id
		{
			get
			{
				return this._advertiser_id;
			}
			set
			{
				if ((this._advertiser_id != value))
				{
					if (this._Advertiser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onadvertiser_idChanging(value);
					this.SendPropertyChanging();
					this._advertiser_id = value;
					this.SendPropertyChanged("advertiser_id");
					this.Onadvertiser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid", DbType="Int NOT NULL")]
		public int pid
		{
			get
			{
				return this._pid;
			}
			set
			{
				if ((this._pid != value))
				{
					this.OnpidChanging(value);
					this.SendPropertyChanging();
					this._pid = value;
					this.SendPropertyChanged("pid");
					this.OnpidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campaign_name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string campaign_name
		{
			get
			{
				return this._campaign_name;
			}
			set
			{
				if ((this._campaign_name != value))
				{
					this.Oncampaign_nameChanging(value);
					this.SendPropertyChanging();
					this._campaign_name = value;
					this.SendPropertyChanged("campaign_name");
					this.Oncampaign_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campaign_type", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string campaign_type
		{
			get
			{
				return this._campaign_type;
			}
			set
			{
				if ((this._campaign_type != value))
				{
					this.Oncampaign_typeChanging(value);
					this.SendPropertyChanging();
					this._campaign_type = value;
					this.SendPropertyChanged("campaign_type");
					this.Oncampaign_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified", DbType="DateTime")]
		public System.Nullable<System.DateTime> modified
		{
			get
			{
				return this._modified;
			}
			set
			{
				if ((this._modified != value))
				{
					this.OnmodifiedChanging(value);
					this.SendPropertyChanging();
					this._modified = value;
					this.SendPropertyChanged("modified");
					this.OnmodifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created", DbType="DateTime")]
		public System.Nullable<System.DateTime> created
		{
			get
			{
				return this._created;
			}
			set
			{
				if ((this._created != value))
				{
					this.OncreatedChanging(value);
					this.SendPropertyChanging();
					this._created = value;
					this.SendPropertyChanged("created");
					this.OncreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Advertiser_Campaign", Storage="_Advertiser", ThisKey="advertiser_id", OtherKey="id", IsForeignKey=true)]
		public Advertiser Advertiser
		{
			get
			{
				return this._Advertiser.Entity;
			}
			set
			{
				Advertiser previousValue = this._Advertiser.Entity;
				if (((previousValue != value) 
							|| (this._Advertiser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Advertiser.Entity = null;
						previousValue.Campaigns.Remove(this);
					}
					this._Advertiser.Entity = value;
					if ((value != null))
					{
						value.Campaigns.Add(this);
						this._advertiser_id = value.id;
					}
					else
					{
						this._advertiser_id = default(int);
					}
					this.SendPropertyChanged("Advertiser");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Advertiser")]
	public partial class Advertiser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private EntitySet<Campaign> _Campaigns;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public Advertiser()
		{
			this._Campaigns = new EntitySet<Campaign>(new Action<Campaign>(this.attach_Campaigns), new Action<Campaign>(this.detach_Campaigns));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Advertiser_Campaign", Storage="_Campaigns", ThisKey="id", OtherKey="advertiser_id")]
		public EntitySet<Campaign> Campaigns
		{
			get
			{
				return this._Campaigns;
			}
			set
			{
				this._Campaigns.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Campaigns(Campaign entity)
		{
			this.SendPropertyChanging();
			entity.Advertiser = this;
		}
		
		private void detach_Campaigns(Campaign entity)
		{
			this.SendPropertyChanging();
			entity.Advertiser = null;
		}
	}
}
#pragma warning restore 1591
