// <auto-generated />
namespace DirectAgents.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TrafficType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TrafficType));
        
        string IMigrationMetadata.Id
        {
            get { return "201209171922380_TrafficType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
