// <auto-generated />
namespace DirectAgents.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Conversions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Conversions));
        
        string IMigrationMetadata.Id
        {
            get { return "201209201838238_Conversions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
