USE [{%COMMON_DATABASE_NAME%}]
GO

ALTER VIEW [dbo].[AccountView2RollupMultiYear] AS

{%SELECT_QUERIES%}
SELECT [Period]
      ,[Publisher]
      ,'' AS [Pub QB Name]
      ,[Advertiser]
      ,[QB Name] AS [Adv QB Name]
      ,[Adv Payment Terms]
      ,[Campaign Number]
      ,[Campaign Name]
      ,[Rev Currency]
      ,[Cost Currency]
      ,[Rev/Unit]
      ,[Rev/Unit USD]
      ,[Cost/Unit]
      ,[Cost/Unit USD]
      ,[Units]
      ,[Unit Type]
      ,[Income Type]
      ,'' AS [Cost Code]
      ,[Revenue]
      ,[Revenue USD]
      ,[Cost]
      ,[Cost USD]
      ,[Margin]
      ,[%Margin]
      ,[Total Campaign Cost USD]
      ,[Media Buyer]
      ,'' AS [Analyst]
      ,[Ad Manager]
      ,[Account Manager]
      ,[Status]
      ,[MediaBuyerApproval Status]
      ,[Accounting Status]
      ,[name]
      ,[Aff Pay Method]
      ,[Pub Pay Curr]
      ,[Pub Payout]
      ,[Percentage of Traffic Generated]
      ,[CampaignNotes]
      ,[Source]
  FROM [DAMain1].[dbo].[AccountView2RollupJan16ToDec16] UNION ALL
SELECT [Period]
      ,[Publisher]
      ,'' AS [Pub QB Name]
      ,[Advertiser]
      ,[QB Name] AS [Adv QB Name]
      ,'' AS [Adv Payment Terms]
      ,[Campaign Number]
      ,[Campaign Name]
      ,[Rev Currency]
      ,[Cost Currency]
      ,[Rev/Unit]
      ,[Rev/Unit USD]
      ,[Cost/Unit]
      ,[Cost/Unit USD]
      ,[Units]
      ,[Unit Type]
      ,'' AS [Income Type]
      ,'' AS [Cost Code]
      ,[Revenue]
      ,[Revenue USD]
      ,[Cost]
      ,[Cost USD]
      ,[Margin]
      ,[%Margin]
      ,[Total Campaign Cost USD]
      ,[Media Buyer]
      ,'' AS [Analyst]
      ,[Ad Manager]
      ,[Account Manager]
      ,[Status]
      ,[MediaBuyerApproval Status]
      ,[Accounting Status]
      ,[name]
      ,[Aff Pay Method]
      ,[Pub Pay Curr]
      ,[Pub Payout]
      ,[Percentage of Traffic Generated]
      ,[CampaignNotes]
      ,[Source]
  FROM [DAMain1].[dbo].[AccountView2RollupJan15ToDec15]


GO


