//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EomApp1.Screens.PaymentBatches
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignPublisherPaymentBatchesSummary
    {
        public string PublisherName { get; set; }
        public string NetTermTypeName { get; set; }
        public string PaymentMethodName { get; set; }
        public string AffiliateCurrencyName { get; set; }
        public Nullable<decimal> SumItemTotalCost { get; set; }
        public string ItemAccountingStatusName { get; set; }
        public Nullable<int> PaymentBatchId { get; set; }
        public string ItemIds { get; set; }
    }
}
