//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace AccountingBackupWeb.Models.DirectTrack.Schemas.Classes.SaleDetail {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/saleDetail/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/saleDetail/v1_0", IsNullable=false)]
    public enum saleType {
        
        /// <remarks/>
        category,
        
        /// <remarks/>
        product,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/saleDetail/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/saleDetail/v1_0", IsNullable=false)]
    public partial class affiliateResourceURL {
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/saleDetail/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/saleDetail/v1_0", IsNullable=false)]
    public partial class campaignResourceURL {
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/saleDetail/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/saleDetail/v1_0", IsNullable=false)]
    public partial class subIDResourceURL {
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/saleDetail/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/saleDetail/v1_0", IsNullable=false)]
    public partial class creativeResourceURL {
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/saleDetail/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/saleDetail/v1_0", IsNullable=false)]
    public partial class creativeDeploymentResourceURL {
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/saleDetail/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/saleDetail/v1_0", IsNullable=false)]
    public partial class lineItem {
        
        private uint quantityField;
        
        private string productIDField;
        
        private booleanInt ownedField;
        
        private bool ownedFieldSpecified;
        
        private string productNameField;
        
        private string productCampaignResourceURLField;
        
        private string lineItemStatusField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string productID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public booleanInt owned {
            get {
                return this.ownedField;
            }
            set {
                this.ownedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ownedSpecified {
            get {
                return this.ownedFieldSpecified;
            }
            set {
                this.ownedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string productName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string productCampaignResourceURL {
            get {
                return this.productCampaignResourceURLField;
            }
            set {
                this.productCampaignResourceURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lineItemStatus {
            get {
                return this.lineItemStatusField;
            }
            set {
                this.lineItemStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.digitalriver.com/directtrack/api/saleDetail/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute("isSubSale", Namespace="http://www.digitalriver.com/directtrack/api/saleDetail/v1_0", IsNullable=false)]
    public enum booleanInt {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/saleDetail/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/saleDetail/v1_0", IsNullable=false)]
    public partial class lineItems {
        
        private lineItem[] lineItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lineItem")]
        public lineItem[] lineItem {
            get {
                return this.lineItemField;
            }
            set {
                this.lineItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/saleDetail/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/saleDetail/v1_0", IsNullable=false)]
    public partial class subIDs {
        
        private string subID1Field;
        
        private string subID2Field;
        
        private string subID3Field;
        
        private string subID4Field;
        
        private string subID5Field;
        
        /// <remarks/>
        public string subID1 {
            get {
                return this.subID1Field;
            }
            set {
                this.subID1Field = value;
            }
        }
        
        /// <remarks/>
        public string subID2 {
            get {
                return this.subID2Field;
            }
            set {
                this.subID2Field = value;
            }
        }
        
        /// <remarks/>
        public string subID3 {
            get {
                return this.subID3Field;
            }
            set {
                this.subID3Field = value;
            }
        }
        
        /// <remarks/>
        public string subID4 {
            get {
                return this.subID4Field;
            }
            set {
                this.subID4Field = value;
            }
        }
        
        /// <remarks/>
        public string subID5 {
            get {
                return this.subID5Field;
            }
            set {
                this.subID5Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.digitalriver.com/directtrack/api/saleDetail/v1_0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.digitalriver.com/directtrack/api/saleDetail/v1_0", IsNullable=false)]
    public partial class saleDetail {
        
        private string transactionIDField;
        
        private string cookieIDField;
        
        private affiliateResourceURL affiliateResourceURLField;
        
        private campaignResourceURL campaignResourceURLField;
        
        private lineItem[] lineItemsField;
        
        private creativeResourceURL creativeResourceURLField;
        
        private creativeDeploymentResourceURL creativeDeploymentResourceURLField;
        
        private string dateField;
        
        private subIDs subIDsField;
        
        private string saleStatusField;
        
        private string saleInfoField;
        
        private string saleRepField;
        
        private string statusDateField;
        
        private string ipAddressField;
        
        private string advOptInfoField;
        
        private uint landingPageIDField;
        
        private bool landingPageIDFieldSpecified;
        
        private uint poolIDField;
        
        private bool poolIDFieldSpecified;
        
        private booleanInt isSubSaleField;
        
        private bool isSubSaleFieldSpecified;
        
        private string currencyField;
        
        private string platformField;
        
        private string siteIDField;
        
        private string localeField;
        
        private string clickDateField;
        
        private booleanInt recordLeadField;
        
        private bool recordLeadFieldSpecified;
        
        private booleanInt deleteSaleField;
        
        private bool deleteSaleFieldSpecified;
        
        private string deleteReasonField;
        
        private string deleteDetailsField;
        
        private saleType saleTypeField;
        
        private bool saleTypeFieldSpecified;
        
        private string refererURLField;
        
        private string locationField;
        
        /// <remarks/>
        public string transactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        public string cookieID {
            get {
                return this.cookieIDField;
            }
            set {
                this.cookieIDField = value;
            }
        }
        
        /// <remarks/>
        public affiliateResourceURL affiliateResourceURL {
            get {
                return this.affiliateResourceURLField;
            }
            set {
                this.affiliateResourceURLField = value;
            }
        }
        
        /// <remarks/>
        public campaignResourceURL campaignResourceURL {
            get {
                return this.campaignResourceURLField;
            }
            set {
                this.campaignResourceURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("lineItem", IsNullable=false)]
        public lineItem[] lineItems {
            get {
                return this.lineItemsField;
            }
            set {
                this.lineItemsField = value;
            }
        }
        
        /// <remarks/>
        public creativeResourceURL creativeResourceURL {
            get {
                return this.creativeResourceURLField;
            }
            set {
                this.creativeResourceURLField = value;
            }
        }
        
        /// <remarks/>
        public creativeDeploymentResourceURL creativeDeploymentResourceURL {
            get {
                return this.creativeDeploymentResourceURLField;
            }
            set {
                this.creativeDeploymentResourceURLField = value;
            }
        }
        
        /// <remarks/>
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public subIDs subIDs {
            get {
                return this.subIDsField;
            }
            set {
                this.subIDsField = value;
            }
        }
        
        /// <remarks/>
        public string saleStatus {
            get {
                return this.saleStatusField;
            }
            set {
                this.saleStatusField = value;
            }
        }
        
        /// <remarks/>
        public string saleInfo {
            get {
                return this.saleInfoField;
            }
            set {
                this.saleInfoField = value;
            }
        }
        
        /// <remarks/>
        public string saleRep {
            get {
                return this.saleRepField;
            }
            set {
                this.saleRepField = value;
            }
        }
        
        /// <remarks/>
        public string statusDate {
            get {
                return this.statusDateField;
            }
            set {
                this.statusDateField = value;
            }
        }
        
        /// <remarks/>
        public string ipAddress {
            get {
                return this.ipAddressField;
            }
            set {
                this.ipAddressField = value;
            }
        }
        
        /// <remarks/>
        public string advOptInfo {
            get {
                return this.advOptInfoField;
            }
            set {
                this.advOptInfoField = value;
            }
        }
        
        /// <remarks/>
        public uint landingPageID {
            get {
                return this.landingPageIDField;
            }
            set {
                this.landingPageIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool landingPageIDSpecified {
            get {
                return this.landingPageIDFieldSpecified;
            }
            set {
                this.landingPageIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint poolID {
            get {
                return this.poolIDField;
            }
            set {
                this.poolIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poolIDSpecified {
            get {
                return this.poolIDFieldSpecified;
            }
            set {
                this.poolIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public booleanInt isSubSale {
            get {
                return this.isSubSaleField;
            }
            set {
                this.isSubSaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isSubSaleSpecified {
            get {
                return this.isSubSaleFieldSpecified;
            }
            set {
                this.isSubSaleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public string platform {
            get {
                return this.platformField;
            }
            set {
                this.platformField = value;
            }
        }
        
        /// <remarks/>
        public string siteID {
            get {
                return this.siteIDField;
            }
            set {
                this.siteIDField = value;
            }
        }
        
        /// <remarks/>
        public string locale {
            get {
                return this.localeField;
            }
            set {
                this.localeField = value;
            }
        }
        
        /// <remarks/>
        public string clickDate {
            get {
                return this.clickDateField;
            }
            set {
                this.clickDateField = value;
            }
        }
        
        /// <remarks/>
        public booleanInt recordLead {
            get {
                return this.recordLeadField;
            }
            set {
                this.recordLeadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool recordLeadSpecified {
            get {
                return this.recordLeadFieldSpecified;
            }
            set {
                this.recordLeadFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public booleanInt deleteSale {
            get {
                return this.deleteSaleField;
            }
            set {
                this.deleteSaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deleteSaleSpecified {
            get {
                return this.deleteSaleFieldSpecified;
            }
            set {
                this.deleteSaleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string deleteReason {
            get {
                return this.deleteReasonField;
            }
            set {
                this.deleteReasonField = value;
            }
        }
        
        /// <remarks/>
        public string deleteDetails {
            get {
                return this.deleteDetailsField;
            }
            set {
                this.deleteDetailsField = value;
            }
        }
        
        /// <remarks/>
        public saleType saleType {
            get {
                return this.saleTypeField;
            }
            set {
                this.saleTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool saleTypeSpecified {
            get {
                return this.saleTypeFieldSpecified;
            }
            set {
                this.saleTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string refererURL {
            get {
                return this.refererURLField;
            }
            set {
                this.refererURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
}
